### ISSUE TITLE
bower install breaks on bower-bourbon

### ISSUE THREAD

**Issue by GordonSchmidt** [opsb/ember-orbit-todos#7]
Hi,

when i follow your installation instructions the 3rd step `bower install` stops with the last line:
`bower bower-bourbon#~3.1.8                 ENOTFOUND Package bower-bourbon not found`

I'm using npm version 1.4.28 and bower version 1.3.12. This error might occur due to outdated dependencies. Can you please update your dependencies, so installation will work again?

Regards Gordon

**Comment by opsb** [comment]
Everything's upgraded and ready to go(ember-cli / orbit / ember-orbit). I don't have time to update the styling dependencies so I've removed them for now (will add them back in when I get a chance). Let me know if you have any trouble.
